name: flutter_application_1
description: "Mantenimiento Preventivo"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  image_picker: ^1.0.7
  signature: ^5.4.0
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#1565C0"
  image: assets/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
        - asset: fonts/Roboto-VariableFont_wdth,wght.ttf
